# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'wiserIos' do

pod 'JSQMessagesViewController'
pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'

end

target 'wiserIosTests' do

end

